# Creates sample dns records to use while debugging the provider
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: records
spec:
  endpoints:
    - dnsName: a.local
      recordType: A
      targets:
        - "11.11.11.11"
        - "22.22.22.22"
    - dnsName: cname.local
      recordType: CNAME
      targets:
        - other1.local
        - other2.local
    - dnsName: mx.local
      recordType: MX
      targets:
        - 1 other1.local
    - dnsName: ns.local
      recordType: NS
      targets:
        - ns
    - dnsName: srv.local
      recordType: SRV
      targets:
        - 1 2 3 other1.local
    - dnsName: txt.local
      recordType: TXT
      targets:
        - hello world
