---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
        # deploy the external-dns controller
        - image: registry.k8s.io/external-dns/external-dns:v0.14.2
          name: controller
          args: ["--source=crd", "--provider=webhook"]
        # deploy the routeros provider
        - name: provider
          image: docker.io/benfiola/external-dns-routeros-provider:latest
          args: ["run"]
          env:
            - name: EXTERNAL_DNS_ROUTEROS_PROVIDER_ROUTEROS_ADDRESS
              value: "127.0.0.1:8728"
            - name: EXTERNAL_DNS_ROUTEROS_PROVIDER_ROUTEROS_PASSWORD
              value: ""
            - name: EXTERNAL_DNS_ROUTEROS_PROVIDER_ROUTEROS_USERNAME
              value: admin
---

